apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-wine-classifier
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-wine-classifier
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mlflow-wine-classifier
    spec:
      containers:
      - args:
        - mlflow models serve -m models:/topics-agenda/26 --host 0.0.0.0 --port 5000 --env-manager=local
        command:
        - /bin/bash
        - -c
        env:
        - name: GUNICORN_CMD_ARGS
          value: --timeout 6000
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/credentials.json
        - name: MLFLOW_TRACKING_URI
          value: http://10.0.8.162:80
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: python
        - name: TRITON_CLIENT_URL
          value: 10.0.4.107:8001
        - name: OPENSEARCH_HOST
          value: '10.128.0.97'
        - name: MEMCACHE_URL
          value: 10.82.1.3:11211
        image: gcr.io/infoxel-tagx/ml/models/topics_agenda:latest
        imagePullPolicy: Always
        name: mlflow-topics-agenda
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: '2'
            memory: 3000Mi
          requests:
            cpu: '0.1'
            memory: 200Mi
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
      nodeSelector:
        ml: nlp
      volumes:
      - name: google-cloud-key
        secret:
          secretName: service-account-credentials
